server:
  address: localhost
  port: 8082

spring:
    # datasource
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://120.77.159.110:3306/data_flow?useSSL=false&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
    # redis 配置
    redis:
      pool:
        min-idle: 0
        max-active: 8
        max-wait: -1
      database: 0
      host: 120.77.159.110
      port: 6379
      password:
      timeout: 0